export const ShopActionTypes = {
    FETCH_COLLECTIONS_START : 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCES : 'FETCH_COLLECTIONS_SUCCES',
    FETCH_COLLECTIONS_FAILURE : 'FETCH_COLLECTIONS_FAILURE'
}